# Generated by Django 5.2.3 on 2025-06-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppFieldUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=64, null=True)),
                ('id_number', models.CharField(max_length=64)),
                ('active_status', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('pass_phrase', models.TextField(blank=True, null=True)),
                ('prefix', models.CharField(blank=True, max_length=64, null=True)),
                ('company', models.IntegerField()),
                ('office', models.IntegerField()),
                ('receipt_format', models.IntegerField(default=1)),
                ('printer_name', models.CharField(max_length=64)),
                ('profile_photo', models.TextField(blank=True, null=True)),
                ('user_level', models.CharField(default='TELLER', max_length=64)),
                ('preview_stages', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'app_field_user',
            },
        ),
    ]
